<a href="https://colab.research.google.com/github/rubykar/Business_Model/blob/main/BusinessModelSentimentAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import pandas as pd
import numpy as np
import re
from nltk.corpus import stopwords
from wordcloud import WordCloud, STOPWORDS
import spacy


data_train = pd.read_csv('/content/training_data.csv')
data_test = pd.read_csv('/content/test_data.csv')
data_train.shape

(40508, 11)

1. **PROCESSING TRAINING DATASET**

In [42]:
data_test.shape

(15424, 9)

In [43]:
data_train.head()

,IDLink,Title,Headline,Source,Topic,PublishDate,Facebook,GooglePlus,LinkedIn,SentimentTitle,SentimentHeadline
0,Tr3CMgRv1N,Obama Lays Wreath at Arlington National Cemetery,Obama Lays Wreath at Arlington National Cemete...,USA TODAY,obama,02-04-2002 00:00,-1,-1,-1,0.000000,-0.053300
1,Wc81vGp8qZ,A Look at the Health of the Chinese Economy,"Tim Haywood, investment director business-unit...",Bloomberg,economy,20-09-2008 00:00,-1,-1,-1,0.208333,-0.156386
2,zNGH03CrZH,Nouriel Roubini: Global Economy Not Back to 2008,"Nouriel Roubini, NYU professor and chairman at...",Bloomberg,economy,28-01-2012 00:00,-1,-1,-1,-0.425210,0.139754
3,3sM1H0W8ts,Finland GDP Expands In Q4,Finland's economy expanded marginally in the t...,RTT News,economy,01-03-2015 00:06,-1,-1,-1,0.000000,0.026064
4,wUbnxgvqaZ,"Tourism, govt spending buoys Thai economy in J...",Tourism and public spending continued to boost...,The Nation - Thailand&#39;s English news,economy,01-03-2015 00:11,-1,-1,-1,0.000000,0.141084

In [44]:
nlp = spacy.load("en_core_web_sm", disable=["parser", "ner"])

In [45]:
############## Converting title and headlines into lowercase ##############
data_train['new_title'] = data_train['Title'].apply(lambda x: " ".join(x.lower() for x in x.split()))
data_train['new_headlines'] = data_train['Headline'].apply(lambda x: " ".join(x.lower() for x in x.split()))
data_train['new_title'].head()

0     obama lays wreath at arlington national cemetery
1          a look at the health of the chinese economy
2     nouriel roubini: global economy not back to 2008
3                            finland gdp expands in q4
4    tourism, govt spending buoys thai economy in j...
Name: new_title, dtype: object

In [46]:
data_train['new_headlines'].head()

0    obama lays wreath at arlington national cemete...
1    tim haywood, investment director business-unit...
2    nouriel roubini, nyu professor and chairman at...
3    finland's economy expanded marginally in the t...
4    tourism and public spending continued to boost...
Name: new_headlines, dtype: object

In [47]:
########## To remove punctuation #######
data_train['new_title'] = data_train['Title'].str.replace('[^\w\s]','')
data_train['new_headlines'] = data_train['Headline'].str.replace('[^\w\s]','')

<ipython-input-47-49f2b7117b02>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  data_train['new_title'] = data_train['Title'].str.replace('[^\w\s]','')
<ipython-input-47-49f2b7117b02>:3: FutureWarning: The default value of regex will change from True to False in a future version.
  data_train['new_headlines'] = data_train['Headline'].str.replace('[^\w\s]','')

In [48]:
data_train['new_title'].head()

0     Obama Lays Wreath at Arlington National Cemetery
1          A Look at the Health of the Chinese Economy
2      Nouriel Roubini Global Economy Not Back to 2008
3                            Finland GDP Expands In Q4
4    Tourism govt spending buoys Thai economy in Ja...
Name: new_title, dtype: object

In [49]:
data_train['new_headlines'].head()

0    Obama Lays Wreath at Arlington National Cemete...
1    Tim Haywood investment director businessunit h...
2    Nouriel Roubini NYU professor and chairman at ...
3    Finlands economy expanded marginally in the th...
4    Tourism and public spending continued to boost...
Name: new_headlines, dtype: object

In [50]:
def remove_emoji(text):
 emoji_pattern = re.compile("["
                        u"\U0001F600-\U0001F64F"  # emoticons
                        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                        u"\U0001F680-\U0001F6FF"  # transport & map symbols
                        u"\U0001F1E0-\U0001F1FF"  # flags 
                        u"\U00002702-\U000027B0"
                        u"\U000024C2-\U0001F251"
                        "]+", flags=re.UNICODE)
 return emoji_pattern.sub(r'', text)
data_train['new_title'] = data_train['Title'].apply(lambda x: remove_emoji(x))
data_train['new_headlines'] = data_train['Headline'].apply(lambda x: remove_emoji(x))

In [51]:
data_train['new_title'].head()

0     Obama Lays Wreath at Arlington National Cemetery
1          A Look at the Health of the Chinese Economy
2     Nouriel Roubini: Global Economy Not Back to 2008
3                            Finland GDP Expands In Q4
4    Tourism, govt spending buoys Thai economy in J...
Name: new_title, dtype: object

In [52]:
data_train['new_headlines'].head()

0    Obama Lays Wreath at Arlington National Cemete...
1    Tim Haywood, investment director business-unit...
2    Nouriel Roubini, NYU professor and chairman at...
3    Finland's economy expanded marginally in the t...
4    Tourism and public spending continued to boost...
Name: new_headlines, dtype: object

In [53]:
################### REMOVING STOP WORDS###################
import nltk
nltk.download('stopwords')
stop = set(stopwords.words('english'))
data_train['new_title'] = data_train['new_title'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))
data_train['new_headlines'] = data_train['new_headlines'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [54]:
data_train['new_headlines'].head(20)

0     Obama Lays Wreath Arlington National Cemetery....
1     Tim Haywood, investment director business-unit...
2     Nouriel Roubini, NYU professor chairman Roubin...
3     Finland's economy expanded marginally three mo...
4     Tourism public spending continued boost econom...
5     Over 100 attendees expected see latest version...
6     RAMALLAH, February 25, 2016 (WAFA) - Palestine...
7     First lady Michelle Obama speaks State Dinning...
8     A Hancock County man lost barn early Monday mo...
9     New Delhi, Feb.29 : Technology giant Microsoft...
10    Microsoft may burned one bridge, still buildin...
11    The platform battles back MWC16 +Analysis Two ...
12    Greece's economy expanded 0.1 percent last yea...
13    Big data analytics Internet Things (IoT) expec...
14    Microsoft’s AR headset made available develope...
15    What A + B? Welcome review Word Mac 2016, upda...
16    The Microsoft Band 2 hit market late 2015 look...
17    It seems Microsoft getting ready push Project ...
18    Greece's economy expanded slightly last three ...
19    Sweden's economy massive tear, country's centr...
Name: new_headlines, dtype: object

In [55]:
data_train['new_title'].head(20)

0         Obama Lays Wreath Arlington National Cemetery
1                         A Look Health Chinese Economy
2         Nouriel Roubini: Global Economy Not Back 2008
3                             Finland GDP Expands In Q4
4     Tourism, govt spending buoys Thai economy January
5     Intellitec Solutions Host 13th Annual Spring M...
6                                   Monday, 29 Feb 2016
7          Obama, stars pay musical tribute Ray Charles
8          Fire claims 100-year-old barn Hancock County
9           Microsoft's new Windows 10 ad targets Apple
10    Microsoft Project Centennial seen “universal” ...
11    Microsoft sneaks onto Android Android sneaks o...
12       Greek economy grows 0.1 pct q/q fourth quarter
13    Big data Internet Things add £322BN UK economy...
14    HoloLens dev edition costs £2,000 new Conker game
15    Microsoft Word Mac 2016 review: A subtle yet m...
16            Microsoft Band 2 gains appeal lower price
17    Microsoft prepares unleash Office 2016 full de...
18    Greek economy shrank 0.3 percent last year exp...
19    Sweden's economy fire — here's that's terrible...
Name: new_title, dtype: object

In [56]:
###############lemmatization using Spacy so that we can count the appearance of each word. Lemmatization removes the grammar tense and transforms each word into its original form. #######
def space(comment):
    doc = nlp(comment)
    return " ".join([token.lemma_ for token in doc])
data_train['new_headlines']= data_train['new_headlines'].apply(space)
data_train.head()

,IDLink,Title,Headline,Source,Topic,PublishDate,Facebook,GooglePlus,LinkedIn,SentimentTitle,SentimentHeadline,new_title,new_headlines
0,Tr3CMgRv1N,Obama Lays Wreath at Arlington National Cemetery,Obama Lays Wreath at Arlington National Cemete...,USA TODAY,obama,02-04-2002 00:00,-1,-1,-1,0.000000,-0.053300,Obama Lays Wreath Arlington National Cemetery,Obama Lays Wreath Arlington National Cemetery ...
1,Wc81vGp8qZ,A Look at the Health of the Chinese Economy,"Tim Haywood, investment director business-unit...",Bloomberg,economy,20-09-2008 00:00,-1,-1,-1,0.208333,-0.156386,A Look Health Chinese Economy,"Tim Haywood , investment director business - u..."
2,zNGH03CrZH,Nouriel Roubini: Global Economy Not Back to 2008,"Nouriel Roubini, NYU professor and chairman at...",Bloomberg,economy,28-01-2012 00:00,-1,-1,-1,-0.425210,0.139754,Nouriel Roubini: Global Economy Not Back 2008,"Nouriel Roubini , NYU professor chairman Roubi..."
3,3sM1H0W8ts,Finland GDP Expands In Q4,Finland's economy expanded marginally in the t...,RTT News,economy,01-03-2015 00:06,-1,-1,-1,0.000000,0.026064,Finland GDP Expands In Q4,Finland 's economy expand marginally three mon...
4,wUbnxgvqaZ,"Tourism, govt spending buoys Thai economy in J...",Tourism and public spending continued to boost...,The Nation - Thailand&#39;s English news,economy,01-03-2015 00:11,-1,-1,-1,0.000000,0.141084,"Tourism, govt spending buoys Thai economy January",tourism public spending continue boost economy...

In [57]:
data_train = data_train.drop(['PublishDate','Title','Source','Headline'],axis = 1)
data_train.head(20)

,IDLink,Topic,Facebook,GooglePlus,LinkedIn,SentimentTitle,SentimentHeadline,new_title,new_headlines
0,Tr3CMgRv1N,obama,-1,-1,-1,0.000000,-0.053300,Obama Lays Wreath Arlington National Cemetery,Obama Lays Wreath Arlington National Cemetery ...
1,Wc81vGp8qZ,economy,-1,-1,-1,0.208333,-0.156386,A Look Health Chinese Economy,"Tim Haywood , investment director business - u..."
2,zNGH03CrZH,economy,-1,-1,-1,-0.425210,0.139754,Nouriel Roubini: Global Economy Not Back 2008,"Nouriel Roubini , NYU professor chairman Roubi..."
3,3sM1H0W8ts,economy,-1,-1,-1,0.000000,0.026064,Finland GDP Expands In Q4,Finland 's economy expand marginally three mon...
4,wUbnxgvqaZ,economy,-1,-1,-1,0.000000,0.141084,"Tourism, govt spending buoys Thai economy January",tourism public spending continue boost economy...
5,1P7kLrnWEp,microsoft,-1,-1,-1,-0.075378,0.036773,Intellitec Solutions Host 13th Annual Spring M...,over 100 attendee expect see late version Micr...
6,lKg2pImhCl,palestine,0,0,0,0.000000,-0.005906,"Monday, 29 Feb 2016","RAMALLAH , February 25 , 2016 ( WAFA ) - Pales..."
7,X2KssRh8hS,obama,-1,-1,-1,0.083333,0.103003,"Obama, stars pay musical tribute Ray Charles",first lady Michelle Obama speak State Dinning ...
8,xCHOHAl8v8,palestine,-1,-1,-1,-0.173925,-0.050185,Fire claims 100-year-old barn Hancock County,a Hancock County man lose barn early Monday mo...
9,OR6Xuthveg,microsoft,-1,-1,-1,-0.059536,-0.081715,Microsoft's new Windows 10 ad targets Apple,"New Delhi , feb.29 : technology giant Microsof..."
10,Xj3f9iYOaj,microsoft,-1,-1,-1,0.000000,0.002550,Microsoft Project Centennial seen “universal” ...,"Microsoft may burn one bridge , still build di..."
11,XP3QOFGatF,microsoft,-1,-1,-1,0.000000,0.052670,Microsoft sneaks onto Android Android sneaks o...,the platform battle back MWC16 + Analysis two ...
12,SMpjcX5Owv,economy,-1,-1,-1,0.000000,-0.375259,Greek economy grows 0.1 pct q/q fourth quarter,Greece 's economy expand 0.1 percent last year...
13,1cSzijNBpx,economy,-1,-1,-1,0.063205,0.038986,Big data Internet Things add £322BN UK economy...,big data analytic internet Things ( IoT ) expe...
14,iKGS4umScz,microsoft,-1,-1,-1,0.000000,0.079434,"HoloLens dev edition costs £2,000 new Conker game",Microsoft ’s AR headset make available develop...
15,hgh3ircFGZ,microsoft,-1,-1,-1,-0.023883,-0.032275,Microsoft Word Mac 2016 review: A subtle yet m...,"what A + b ? welcome review Word Mac 2016 , up..."
16,3o1xzPpavu,microsoft,-1,-1,-1,-0.070868,0.000000,Microsoft Band 2 gains appeal lower price,the Microsoft Band 2 hit market late 2015 look...
17,ukPNQD9k4r,microsoft,-1,-1,-1,0.000000,0.001367,Microsoft prepares unleash Office 2016 full de...,it seem Microsoft get ready push Project Cente...
18,5rnVCZqWr2,economy,-1,-1,-1,-0.085645,-0.099531,Greek economy shrank 0.3 percent last year exp...,Greece 's economy expand slightly last three m...
19,CZLVHanbC2,economy,-1,-1,-1,0.000000,-0.014174,Sweden's economy fire — here's that's terrible...,"Sweden 's economy massive tear , country 's ce..."

# 3. **TRAINING AND BUILDING THE MODEL**

In [58]:
pip install scikit-learn-intelex ## Using Scikit learn library

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: scikit-learn-intelex in /usr/local/lib/python3.9/dist-packages (2023.0.1)
Requirement already satisfied: daal4py==2023.0.1 in /usr/local/lib/python3.9/dist-packages (from scikit-learn-intelex) (2023.0.1)
Requirement already satisfied: scikit-learn>=0.22 in /usr/local/lib/python3.9/dist-packages (from scikit-learn-intelex) (1.2.2)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.9/dist-packages (from daal4py==2023.0.1->scikit-learn-intelex) (1.22.4)
Requirement already satisfied: daal==2023.0.1 in /usr/local/lib/python3.9/dist-packages (from daal4py==2023.0.1->scikit-learn-intelex) (2023.0.1)
Requirement already satisfied: tbb==2021.* in /usr/local/lib/python3.9/dist-packages (from daal==2023.0.1->daal4py==2023.0.1->scikit-learn-intelex) (2021.8.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from scikit-learn>=0.22->scikit-learn-intelex) (1.1.1)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.9/dist-packages (from scikit-learn>=0.22->scikit-learn-intelex) (1.10.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-learn>=0.22->scikit-learn-intelex) (3.1.0)

In [59]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import chi2, SelectKBest
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearnex import patch_sklearn

# Extract features from the title
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(data_train['new_title'])
# Convert the sentiment to categorical labels
bins = [-1, -0.5, 0, 0.5, 1, 2]  # add an additional bin edge for positive sentiment
labels = ['negative', 'somewhat negative', 'neutral', 'somewhat positive', 'positive']
y = pd.cut(data_train['SentimentTitle'], bins=bins, labels=labels)

# Perform feature selection
selector = SelectKBest(chi2, k=1000)
X_new = selector.fit_transform(X, y)

# Get the most important feature indices
indices = selector.get_support(indices=True)

# Get the corresponding feature names
features = vectorizer.get_feature_names_out()
important_features = [features[i] for i in indices]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.2, random_state=42)
print(X,y)

# Initialize the OneAPI estimator
patch_sklearn()

# from sklearnex import enable_ipp, enable_mkl  # Required to use OneAPI
# enable_ipp()
# enable_mkl()

estimator = LogisticRegression(max_iter=1000, n_jobs=-1, solver='saga')

# Train the model
estimator.fit(X_train, y_train)
print(X_train)
# Make predictions on the testing set
y_pred = estimator.predict(X_test)

# Evaluate the model performance
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)
y_pred
# # Train a logistic regression model
# model = LogisticRegression()
# model.fit(X_train, y_train)

# # Make predictions on the testing set
# y_pred = model.predict(X_test)

# # Evaluate the model performance
# accuracy = accuracy_score(y_test, y_pred)
# print('Accuracy:', accuracy)

  (0, 3389)	0.46269251221228386
  (0, 12176)	0.3132415956491859
  (0, 1601)	0.514469303169076
  (0, 20089)	0.514469303169076
  (0, 10523)	0.3837992313327171
  (0, 12580)	0.10552802528098273
  (1, 6097)	0.2005693580883672
  (1, 3603)	0.5146245165673135
  (1, 8553)	0.5782680415887448
  (1, 10891)	0.6004495079696519
  (2, 208)	0.42564345760442523
  (2, 1948)	0.3149970860732047
  (2, 12479)	0.3086897109394778
  (2, 7965)	0.24836598066458493
  (2, 15663)	0.5188476221214048
  (2, 12501)	0.5284831620931315
  (2, 6097)	0.11887883400996675
  (3, 14426)	0.4523015005876322
  (3, 9248)	0.31658039534489874
  (3, 6743)	0.4270695386523542
  (3, 7817)	0.4055236273166332
  (3, 7228)	0.5902223332716828
  (4, 9848)	0.35968156738043805
  (4, 18230)	0.41089821942047833
  (4, 3016)	0.5435398699064575
  :	:
  (40504, 7573)	0.2969858478511971
  (40504, 18925)	0.26662752004787127
  (40505, 14230)	0.5498797077418549
  (40505, 5169)	0.4868922490420052
  (40505, 19263)	0.33368259692367763
  (40505, 9769)	0.25823251877273634
  (40505, 13113)	0.2549636863641763
  (40505, 18937)	0.3312234125117382
  (40505, 6353)	0.32836672370198816
  (40506, 15712)	0.4035399830587854
  (40506, 9179)	0.39585412527285385
  (40506, 4686)	0.39889938135035463
  (40506, 10773)	0.49813387771472073
  (40506, 853)	0.44140566265591946
  (40506, 12306)	0.24634561249719128
  (40506, 12580)	0.13293531204029713
  (40507, 1461)	0.477351899832206
  (40507, 18503)	0.4840405197820477
  (40507, 15884)	0.30240108127303916
  (40507, 3809)	0.2879434245762005
  (40507, 6091)	0.22197476480699768
  (40507, 7488)	0.3332730494054296
  (40507, 3089)	0.3376956475823145
  (40507, 13635)	0.2766236054469485
  (40507, 12580)	0.11215800491410315 0        somewhat negative
1                  neutral
2        somewhat negative
3        somewhat negative
4        somewhat negative
               ...
40503             negative
40504              neutral
40505    somewhat negative
40506    somewhat negative
40507             negative
Name: SentimentTitle, Length: 40508, dtype: category
Categories (5, object): ['negative' < 'somewhat negative' < 'neutral' < 'somewhat positive' <
                         'positive']

Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)

  (0, 598)	0.11883473094191378
  (1, 931)	0.3106483731574603
  (1, 459)	0.26050305534645535
  (1, 971)	0.26621123500893096
  (1, 787)	0.31444108780636226
  (1, 598)	0.10269878352473316
  (2, 121)	0.43975811315567515
  (2, 752)	0.37156667019246975
  (3, 519)	0.5347069082713326
  (3, 424)	0.5316781400646033
  (3, 20)	0.35792203726846566
  (3, 584)	0.25758191324294477
  (3, 598)	0.13899874921976949
  (4, 973)	0.5264183380086042
  (4, 594)	0.5151080443936509
  (4, 397)	0.3661129976041866
  (5, 491)	0.28645732269258656
  (5, 622)	0.23487254544879255
  (5, 457)	0.4047646976351852
  (6, 560)	0.15254250725676774
  (7, 715)	0.43270174848704757
  (7, 598)	0.1318801446287163
  (8, 754)	0.3851659797306479
  (9, 550)	0.3025864713616706
  (9, 163)	0.23691300806641954
  :	:
  (32391, 491)	0.3632861836370236
  (32391, 622)	0.29786618779780083
  (32392, 799)	0.42421720460682993
  (32393, 606)	0.22703627060634377
  (32393, 374)	0.28297488080961275
  (32393, 598)	0.09553109768152439
  (32394, 337)	0.35507868374841367
  (32395, 134)	0.27340512942966155
  (32395, 288)	0.21755946094209885
  (32395, 738)	0.30743442602726595
  (32396, 560)	0.10990929339942201
  (32397, 269)	0.3503976461652755
  (32398, 965)	0.5268481322233515
  (32398, 163)	0.3083596785120176
  (32399, 599)	0.3689731484563267
  (32399, 598)	0.09937816978623183
  (32400, 118)	0.38299424958397976
  (32402, 592)	0.30945521080289823
  (32402, 598)	0.11862898557920752
  (32403, 350)	0.3885883299355084
  (32403, 598)	0.1290608633261887
  (32404, 883)	0.3269375364881187
  (32404, 64)	0.3020260472969699
  (32404, 560)	0.12471004353708644
  (32405, 832)	0.3037752492449813
Accuracy: 0.7885707232782029

array(['neutral', 'somewhat negative', 'somewhat negative', ...,
       'somewhat negative', 'neutral', 'neutral'], dtype=object)

In [60]:
import keras
from keras.layers import Dense
ann = keras.models.Sequential([
                                Dense(6, activation="relu",
                                input_shape=X_train.shape[1:]),
                                Dense(6,activation="relu"),
                                Dense(1)
                                ])

optimizer=keras.optimizers.Adam()
loss=keras.losses.mean_squared_error
ann.compile(optimizer=optimizer,loss=loss,metrics=["mean_squared_error"])
# Extract features from the title
# vectorizer = TfidfVectorizer()
# X = vectorizer.fit_transform(data_train['new_title'])
# # Convert the sentiment to categorical labels
# bins = [-1, -0.5, 0, 0.5, 1, 2]  # add an additional bin edge for positive sentiment
# labels = ['negative', 'somewhat negative', 'neutral', 'somewhat positive', 'positive']
y = data_train['SentimentTitle']


# # Perform feature selection
# selector = SelectKBest(chi2, k=1000)
# X_new = selector.fit_transform(X, y)

# # Get the most important feature indices
# indices = selector.get_support(indices=True)

# # Get the corresponding feature names
# features = vectorizer.get_feature_names_out()
# important_features = [features[i] for i in indices]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.2, random_state=42)
X_train = X_train.toarray()
history=ann.fit(X_train,y_train,epochs=100)

ann.summary()

# print_error(X_test,y_test,ann)

Epoch 1/100
1013/1013 [==============================] - 6s 5ms/step - loss: 0.0119 - mean_squared_error: 0.0119
Epoch 2/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0090 - mean_squared_error: 0.0090
Epoch 3/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0087 - mean_squared_error: 0.0087
Epoch 4/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0085 - mean_squared_error: 0.0085
Epoch 5/100
1013/1013 [==============================] - 5s 5ms/step - loss: 0.0083 - mean_squared_error: 0.0083
Epoch 6/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0082 - mean_squared_error: 0.0082
Epoch 7/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0080 - mean_squared_error: 0.0080
Epoch 8/100
1013/1013 [==============================] - 4s 4ms/step - loss: 0.0079 - mean_squared_error: 0.0079
Epoch 9/100
1013/1013 [==============================] - 4s 4ms/step - loss: 0.0078 - mean_squared_error: 0.0078
Epoch 10/100
1013/1013 [==============================] - 4s 4ms/step - loss: 0.0078 - mean_squared_error: 0.0078
Epoch 11/100
1013/1013 [==============================] - 4s 4ms/step - loss: 0.0077 - mean_squared_error: 0.0077
Epoch 12/100
1013/1013 [==============================] - 5s 5ms/step - loss: 0.0076 - mean_squared_error: 0.0076
Epoch 13/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0075 - mean_squared_error: 0.0075
Epoch 14/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0075 - mean_squared_error: 0.0075
Epoch 15/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0074 - mean_squared_error: 0.0074
Epoch 16/100
1013/1013 [==============================] - 5s 5ms/step - loss: 0.0074 - mean_squared_error: 0.0074
Epoch 17/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0074 - mean_squared_error: 0.0074
Epoch 18/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0073 - mean_squared_error: 0.0073
Epoch 19/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0073 - mean_squared_error: 0.0073
Epoch 20/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0073 - mean_squared_error: 0.0073
Epoch 21/100
1013/1013 [==============================] - 6s 6ms/step - loss: 0.0072 - mean_squared_error: 0.0072
Epoch 22/100
1013/1013 [==============================] - 4s 4ms/step - loss: 0.0072 - mean_squared_error: 0.0072
Epoch 23/100
1013/1013 [==============================] - 5s 5ms/step - loss: 0.0072 - mean_squared_error: 0.0072
Epoch 24/100
1013/1013 [==============================] - 5s 5ms/step - loss: 0.0071 - mean_squared_error: 0.0071
Epoch 25/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0071 - mean_squared_error: 0.0071
Epoch 26/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0071 - mean_squared_error: 0.0071
Epoch 27/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0071 - mean_squared_error: 0.0071
Epoch 28/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0070 - mean_squared_error: 0.0070
Epoch 29/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0070 - mean_squared_error: 0.0070
Epoch 30/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0070 - mean_squared_error: 0.0070
Epoch 31/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0070 - mean_squared_error: 0.0070
Epoch 32/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0070 - mean_squared_error: 0.0070
Epoch 33/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0070 - mean_squared_error: 0.0070
Epoch 34/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0069 - mean_squared_error: 0.0069
Epoch 35/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0069 - mean_squared_error: 0.0069
Epoch 36/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0069 - mean_squared_error: 0.0069
Epoch 37/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0069 - mean_squared_error: 0.0069
Epoch 38/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0069 - mean_squared_error: 0.0069
Epoch 39/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0069 - mean_squared_error: 0.0069
Epoch 40/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0068 - mean_squared_error: 0.0068
Epoch 41/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0068 - mean_squared_error: 0.0068
Epoch 42/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0068 - mean_squared_error: 0.0068
Epoch 43/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0068 - mean_squared_error: 0.0068
Epoch 44/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0068 - mean_squared_error: 0.0068
Epoch 45/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0068 - mean_squared_error: 0.0068
Epoch 46/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0068 - mean_squared_error: 0.0068
Epoch 47/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0068 - mean_squared_error: 0.0068
Epoch 48/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0068 - mean_squared_error: 0.0068
Epoch 49/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0068 - mean_squared_error: 0.0068
Epoch 50/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0068 - mean_squared_error: 0.0068
Epoch 51/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0067 - mean_squared_error: 0.0067
Epoch 52/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0067 - mean_squared_error: 0.0067
Epoch 53/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0067 - mean_squared_error: 0.0067
Epoch 54/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0067 - mean_squared_error: 0.0067
Epoch 55/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0067 - mean_squared_error: 0.0067
Epoch 56/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0067 - mean_squared_error: 0.0067
Epoch 57/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0067 - mean_squared_error: 0.0067
Epoch 58/100
1013/1013 [==============================] - 4s 4ms/step - loss: 0.0067 - mean_squared_error: 0.0067
Epoch 59/100
1013/1013 [==============================] - 4s 4ms/step - loss: 0.0067 - mean_squared_error: 0.0067
Epoch 60/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0067 - mean_squared_error: 0.0067
Epoch 61/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0067 - mean_squared_error: 0.0067
Epoch 62/100
1013/1013 [==============================] - 4s 3ms/step - loss: 0.0067 - mean_squared_error: 0.0067
Epoch 63/100
1013/1013 [==============================] - 4s 3ms/step - loss: 0.0067 - mean_squared_error: 0.0067
Epoch 64/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0067 - mean_squared_error: 0.0067
Epoch 65/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 66/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0067 - mean_squared_error: 0.0067
Epoch 67/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 68/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 69/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 70/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 71/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 72/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 73/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 74/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 75/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 76/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 77/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 78/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 79/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 80/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 81/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 82/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 83/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 84/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 85/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 86/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 87/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 88/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 89/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0065 - mean_squared_error: 0.0065
Epoch 90/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0065 - mean_squared_error: 0.0065
Epoch 91/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0065 - mean_squared_error: 0.0065
Epoch 92/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0066 - mean_squared_error: 0.0066
Epoch 93/100
1013/1013 [==============================] - 4s 4ms/step - loss: 0.0065 - mean_squared_error: 0.0065
Epoch 94/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0065 - mean_squared_error: 0.0065
Epoch 95/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0065 - mean_squared_error: 0.0065
Epoch 96/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0065 - mean_squared_error: 0.0065
Epoch 97/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0065 - mean_squared_error: 0.0065
Epoch 98/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0065 - mean_squared_error: 0.0065
Epoch 99/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0065 - mean_squared_error: 0.0065
Epoch 100/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0065 - mean_squared_error: 0.0065
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 6)                 6006

 dense_1 (Dense)             (None, 6)                 42

 dense_2 (Dense)             (None, 1)                 7

=================================================================
Total params: 6,055
Trainable params: 6,055
Non-trainable params: 0
_________________________________________________________________

In [61]:
#Saving Scikitlearn models
import joblib
joblib.dump(estimator, "estimator_Businessmodel.pkl")

# Saving Keras Artificial Neural Network model
ann.save("ann_Businessmodel.h5")

In [62]:
from keras.models import load_model
model = load_model("/content/ann_Businessmodel.h5")

4. TRAINING MODEL BASED ON THE HEADLINES

In [88]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import chi2, SelectKBest
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearnex import patch_sklearn

# Extract features from the title
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(data_train['new_headlines'])
# Convert the sentiment to categorical labels
bins = [-1, -0.5, 0, 0.5, 1, 2]  # add an additional bin edge for positive sentiment
labels = ['negative', 'somewhat negative', 'neutral', 'somewhat positive', 'positive']
y = pd.cut(data_train['SentimentHeadline'], bins=bins, labels=labels)

# Perform feature selection
selector = SelectKBest(chi2, k=1000)
X_new = selector.fit_transform(X, y)

# Get the most important feature indices
indices = selector.get_support(indices=True)

# Get the corresponding feature names
features = vectorizer.get_feature_names_out()
important_features = [features[i] for i in indices]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.2, random_state=42)
print(X,y)

# Initialize the OneAPI estimator
patch_sklearn()

# from sklearnex import enable_ipp, enable_mkl  # Required to use OneAPI
# enable_ipp()
# enable_mkl()

estimator = LogisticRegression(max_iter=1000, n_jobs=-1, solver='saga')

# Train the model
estimator.fit(X_train, y_train)
print(X_train)
# Make predictions on the testing set
y_pred = estimator.predict(X_test)

# Evaluate the model performance
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)
y_pred
# # Train a logistic regression model
# model = LogisticRegression()
# model.fit(X_train, y_train)

# # Make predictions on the testing set
# y_pred = model.predict(X_test)

# # Evaluate the model performance
# accuracy = accuracy_score(y_test, y_pred)
# print('Accuracy:', accuracy)

  (0, 11617)	0.22161307365195831
  (0, 25583)	0.3299175226288903
  (0, 24727)	0.2561026344089701
  (0, 14390)	0.19477148772394717
  (0, 2928)	0.09051097398410887
  (0, 19182)	0.0748069665171653
  (0, 4677)	0.29671423820178244
  (0, 16628)	0.14883789741029996
  (0, 2250)	0.3022245302036695
  (0, 26948)	0.6353263565262811
  (0, 14158)	0.31766317826314056
  (0, 17261)	0.13655791365303432
  (1, 7992)	0.08530918593620224
  (1, 23263)	0.1391953572215712
  (1, 3754)	0.22279113174577345
  (1, 3171)	0.34125847929289704
  (1, 4945)	0.15899958407109172
  (1, 7345)	0.1972301180643018
  (1, 10084)	0.3854058330713312
  (1, 12249)	0.23913750434542036
  (1, 9479)	0.24422836821401972
  (1, 11213)	0.2007105245851438
  (1, 25561)	0.27495202799434326
  (1, 4219)	0.16066541785836613
  (1, 7271)	0.22875891298073367
  :	:
  (40506, 5544)	0.20849574697646509
  (40506, 4484)	0.2594904966402708
  (40506, 5420)	0.2877977358839936
  (40506, 5268)	0.19245229298220806
  (40506, 22932)	0.1918481224327854
  (40506, 25124)	0.14506624215962569
  (40506, 11494)	0.19315612709123894
  (40506, 1171)	0.24192969306955778
  (40506, 14084)	0.16288918117434878
  (40507, 3310)	0.272148244478971
  (40507, 21444)	0.26734141267431166
  (40507, 6869)	0.24767475789116478
  (40507, 22978)	0.3212843543693017
  (40507, 4755)	0.2928986642311806
  (40507, 7990)	0.234945480079193
  (40507, 9717)	0.2326900767507824
  (40507, 9767)	0.24767475789116478
  (40507, 1833)	0.24441852271315354
  (40507, 26630)	0.258763163579
  (40507, 7984)	0.1422199811707416
  (40507, 6044)	0.19714144473808054
  (40507, 6660)	0.2510597508080485
  (40507, 11262)	0.3267584100760632
  (40507, 18690)	0.19291207490809847
  (40507, 26884)	0.2015287309037761 0        somewhat negative
1        somewhat negative
2                  neutral
3                  neutral
4                  neutral
               ...
40503    somewhat negative
40504    somewhat negative
40505              neutral
40506              neutral
40507    somewhat negative
Name: SentimentHeadline, Length: 40508, dtype: category
Categories (5, object): ['negative' < 'somewhat negative' < 'neutral' < 'somewhat positive' <
                         'positive']

Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)

  (0, 430)	0.324209227209815
  (0, 347)	0.2539643450285989
  (0, 822)	0.1950143411900682
  (1, 971)	0.163172458340907
  (1, 934)	0.17203070251627778
  (1, 702)	0.26238464417889257
  (1, 431)	0.16721886161441835
  (1, 977)	0.17174681810414083
  (2, 359)	0.23907727244325638
  (2, 706)	0.23093255571711638
  (2, 105)	0.2610243015612999
  (2, 283)	0.1382090324661504
  (2, 402)	0.16653959067361213
  (3, 343)	0.15499134409958243
  (3, 342)	0.09470505496507466
  (3, 37)	0.08899703572127506
  (3, 52)	0.11057946247376296
  (3, 733)	0.10758462818612245
  (3, 586)	0.06435790990505341
  (3, 995)	0.06243961503646106
  (3, 199)	0.09378349198300902
  (4, 830)	0.23435044385847073
  (4, 712)	0.25982940943692
  (4, 641)	0.5601951330220504
  (4, 209)	0.19341370644069666
  :	:
  (32401, 822)	0.11808937029253917
  (32402, 768)	0.35537525075219767
  (32402, 879)	0.3092117885513688
  (32402, 662)	0.3477862631971644
  (32402, 815)	0.29125365693791605
  (32402, 959)	0.2771431388708517
  (32403, 342)	0.13069188116801372
  (32403, 37)	0.12281488058984501
  (32403, 255)	0.16114577303726788
  (32403, 323)	0.1326526149556322
  (32403, 763)	0.13535005294057206
  (32403, 290)	0.1427165163041639
  (32403, 311)	0.1935310496703032
  (32403, 972)	0.12559326254719527
  (32403, 543)	0.10855647715529096
  (32403, 867)	0.1404435540611971
  (32403, 995)	0.08616594701867886
  (32403, 431)	0.11855964085040438
  (32403, 977)	0.12177000175123152
  (32403, 118)	0.14870611934042252
  (32404, 769)	0.38259342341152003
  (32404, 562)	0.10154485804544583
  (32405, 585)	0.19659849162074855
  (32405, 140)	0.17161910752462384
  (32405, 625)	0.12041369309766567
Accuracy: 0.72772155023451

array(['neutral', 'somewhat negative', 'somewhat negative', ...,
       'somewhat negative', 'somewhat negative', 'somewhat negative'],
      dtype=object)

In [89]:
import keras
from keras.layers import Dense
ann = keras.models.Sequential([
                                Dense(6, activation="relu",
                                input_shape=X_train.shape[1:]),
                                Dense(6,activation="relu"),
                                Dense(1)
                                ])

optimizer=keras.optimizers.Adam()
loss=keras.losses.mean_squared_error
ann.compile(optimizer=optimizer,loss=loss,metrics=["mean_squared_error"])
# Extract features from the title
# vectorizer = TfidfVectorizer()
# X = vectorizer.fit_transform(data_train['new_title'])
# # Convert the sentiment to categorical labels
# bins = [-1, -0.5, 0, 0.5, 1, 2]  # add an additional bin edge for positive sentiment
# labels = ['negative', 'somewhat negative', 'neutral', 'somewhat positive', 'positive']
y = data_train['SentimentHeadline']


# # Perform feature selection
# selector = SelectKBest(chi2, k=1000)
# X_new = selector.fit_transform(X, y)

# # Get the most important feature indices
# indices = selector.get_support(indices=True)

# # Get the corresponding feature names
# features = vectorizer.get_feature_names_out()
# important_features = [features[i] for i in indices]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.2, random_state=42)
X_train = X_train.toarray()
history=ann.fit(X_train,y_train,epochs=100)

ann.summary()

# print_error(X_test,y_test,ann)

Epoch 1/100
1013/1013 [==============================] - 8s 7ms/step - loss: 0.0147 - mean_squared_error: 0.0147
Epoch 2/100
1013/1013 [==============================] - 5s 5ms/step - loss: 0.0125 - mean_squared_error: 0.0125
Epoch 3/100
1013/1013 [==============================] - 6s 6ms/step - loss: 0.0122 - mean_squared_error: 0.0122
Epoch 4/100
1013/1013 [==============================] - 5s 5ms/step - loss: 0.0120 - mean_squared_error: 0.0120
Epoch 5/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0118 - mean_squared_error: 0.0118
Epoch 6/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0116 - mean_squared_error: 0.0116
Epoch 7/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0115 - mean_squared_error: 0.0115
Epoch 8/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0113 - mean_squared_error: 0.0113
Epoch 9/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0112 - mean_squared_error: 0.0112
Epoch 10/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0111 - mean_squared_error: 0.0111
Epoch 11/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0110 - mean_squared_error: 0.0110
Epoch 12/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0109 - mean_squared_error: 0.0109
Epoch 13/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0108 - mean_squared_error: 0.0108
Epoch 14/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0107 - mean_squared_error: 0.0107
Epoch 15/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0107 - mean_squared_error: 0.0107
Epoch 16/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0106 - mean_squared_error: 0.0106
Epoch 17/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0106 - mean_squared_error: 0.0106
Epoch 18/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0105 - mean_squared_error: 0.0105
Epoch 19/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0105 - mean_squared_error: 0.0105
Epoch 20/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0104 - mean_squared_error: 0.0104
Epoch 21/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0104 - mean_squared_error: 0.0104
Epoch 22/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0103 - mean_squared_error: 0.0103
Epoch 23/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0103 - mean_squared_error: 0.0103
Epoch 24/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0102 - mean_squared_error: 0.0102
Epoch 25/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0102 - mean_squared_error: 0.0102
Epoch 26/100
1013/1013 [==============================] - 4s 4ms/step - loss: 0.0101 - mean_squared_error: 0.0101
Epoch 27/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0101 - mean_squared_error: 0.0101
Epoch 28/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0101 - mean_squared_error: 0.0101
Epoch 29/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0101 - mean_squared_error: 0.0101
Epoch 30/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0100 - mean_squared_error: 0.0100
Epoch 31/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0100 - mean_squared_error: 0.0100
Epoch 32/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0099 - mean_squared_error: 0.0099
Epoch 33/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0099 - mean_squared_error: 0.0099
Epoch 34/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0099 - mean_squared_error: 0.0099
Epoch 35/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0099 - mean_squared_error: 0.0099
Epoch 36/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0099 - mean_squared_error: 0.0099
Epoch 37/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0098 - mean_squared_error: 0.0098
Epoch 38/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0098 - mean_squared_error: 0.0098
Epoch 39/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0098 - mean_squared_error: 0.0098
Epoch 40/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0098 - mean_squared_error: 0.0098
Epoch 41/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0098 - mean_squared_error: 0.0098
Epoch 42/100
1013/1013 [==============================] - 4s 4ms/step - loss: 0.0097 - mean_squared_error: 0.0097
Epoch 43/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0097 - mean_squared_error: 0.0097
Epoch 44/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0097 - mean_squared_error: 0.0097
Epoch 45/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0097 - mean_squared_error: 0.0097
Epoch 46/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0097 - mean_squared_error: 0.0097
Epoch 47/100
1013/1013 [==============================] - 3s 2ms/step - loss: 0.0096 - mean_squared_error: 0.0096
Epoch 48/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0096 - mean_squared_error: 0.0096
Epoch 49/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0096 - mean_squared_error: 0.0096
Epoch 50/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0096 - mean_squared_error: 0.0096
Epoch 51/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0096 - mean_squared_error: 0.0096
Epoch 52/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0096 - mean_squared_error: 0.0096
Epoch 53/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0096 - mean_squared_error: 0.0096
Epoch 54/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0096 - mean_squared_error: 0.0096
Epoch 55/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0095 - mean_squared_error: 0.0095
Epoch 56/100
1013/1013 [==============================] - 4s 4ms/step - loss: 0.0095 - mean_squared_error: 0.0095
Epoch 57/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0095 - mean_squared_error: 0.0095
Epoch 58/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0095 - mean_squared_error: 0.0095
Epoch 59/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0095 - mean_squared_error: 0.0095
Epoch 60/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0095 - mean_squared_error: 0.0095
Epoch 61/100
1013/1013 [==============================] - 4s 4ms/step - loss: 0.0095 - mean_squared_error: 0.0095
Epoch 62/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0095 - mean_squared_error: 0.0095
Epoch 63/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0095 - mean_squared_error: 0.0095
Epoch 64/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0095 - mean_squared_error: 0.0095
Epoch 65/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0094 - mean_squared_error: 0.0094
Epoch 66/100
1013/1013 [==============================] - 5s 5ms/step - loss: 0.0095 - mean_squared_error: 0.0095
Epoch 67/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0094 - mean_squared_error: 0.0094
Epoch 68/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0094 - mean_squared_error: 0.0094
Epoch 69/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0094 - mean_squared_error: 0.0094
Epoch 70/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0094 - mean_squared_error: 0.0094
Epoch 71/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0094 - mean_squared_error: 0.0094
Epoch 72/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0094 - mean_squared_error: 0.0094
Epoch 73/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0094 - mean_squared_error: 0.0094
Epoch 74/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0094 - mean_squared_error: 0.0094
Epoch 75/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0094 - mean_squared_error: 0.0094
Epoch 76/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0094 - mean_squared_error: 0.0094
Epoch 77/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0094 - mean_squared_error: 0.0094
Epoch 78/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0093 - mean_squared_error: 0.0093
Epoch 79/100
1013/1013 [==============================] - 3s 2ms/step - loss: 0.0093 - mean_squared_error: 0.0093
Epoch 80/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0094 - mean_squared_error: 0.0094
Epoch 81/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0093 - mean_squared_error: 0.0093
Epoch 82/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0093 - mean_squared_error: 0.0093
Epoch 83/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0093 - mean_squared_error: 0.0093
Epoch 84/100
1013/1013 [==============================] - 3s 2ms/step - loss: 0.0093 - mean_squared_error: 0.0093
Epoch 85/100
1013/1013 [==============================] - 4s 4ms/step - loss: 0.0093 - mean_squared_error: 0.0093
Epoch 86/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0093 - mean_squared_error: 0.0093
Epoch 87/100
1013/1013 [==============================] - 3s 2ms/step - loss: 0.0093 - mean_squared_error: 0.0093
Epoch 88/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0093 - mean_squared_error: 0.0093
Epoch 89/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0093 - mean_squared_error: 0.0093
Epoch 90/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0093 - mean_squared_error: 0.0093
Epoch 91/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0093 - mean_squared_error: 0.0093
Epoch 92/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0093 - mean_squared_error: 0.0093
Epoch 93/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0093 - mean_squared_error: 0.0093
Epoch 94/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0093 - mean_squared_error: 0.0093
Epoch 95/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0093 - mean_squared_error: 0.0093
Epoch 96/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0092 - mean_squared_error: 0.0092
Epoch 97/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0093 - mean_squared_error: 0.0093
Epoch 98/100
1013/1013 [==============================] - 2s 2ms/step - loss: 0.0092 - mean_squared_error: 0.0092
Epoch 99/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0092 - mean_squared_error: 0.0092
Epoch 100/100
1013/1013 [==============================] - 3s 3ms/step - loss: 0.0092 - mean_squared_error: 0.0092
Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_12 (Dense)            (None, 6)                 6006

 dense_13 (Dense)            (None, 6)                 42

 dense_14 (Dense)            (None, 1)                 7

=================================================================
Total params: 6,055
Trainable params: 6,055
Non-trainable params: 0
_________________________________________________________________

2. **DATA PROCESSING FOR TEST DATASET**


DO WE NEED TO PROCESS OUR TEST DATASET ?

Yes, it is important to process your test dataset before using it to evaluate your machine learning model. Data processing involves various steps such as cleaning, normalization, feature engineering, and encoding. These steps help to ensure that the test data is in the same format and range as the training data, and that it does not contain any missing values or outliers.

Processing the test dataset is necessary to make sure that the evaluation of the model is fair and accurate. If the test dataset is not processed, it may lead to inaccurate evaluation metrics and unreliable performance estimates. This can result in poor model performance when the model is deployed in real-world scenarios.

Therefore, it is recommended to apply the same data processing steps to the test dataset that were applied to the training dataset. This ensures that the test data is consistent with the training data, and that the model is evaluated on data that is representative of the real-world scenario it is intended for.

In [64]:
data_test.head()

,IDLink,Title,Headline,Source,Topic,PublishDate,Facebook,GooglePlus,LinkedIn
0,BJ8bLZcYcm,How Millennials Are Changing The Global Economy,But though millennials may have been born into...,Seeking Alpha,economy,17-02-2016 19:09,6,0,3
1,ph8TGKbvNp,China Promises It Will Keep Its Economy Strong,"""""""China's economic fundamentals have not chan...",Fortune,economy,17-02-2016 19:10,5,1,1
2,qJDgUHX7Ay,Fed eyes increased risks for US economy,Many Federal Reserve policymakers saw increase...,Financial Times,economy,17-02-2016 19:10,45,2,40
3,2MVdzsl9s1,Obama to visit Cuba next month: reports,US President Barack Obama will make a historic...,AFP via Yahoo! News,obama,17-02-2016 19:12,17,0,0
4,6QFCqKq50Q,White House: Obama Will Not Attend Justice Sca...,President Barack Obama will not attend Justice...,NBCNews.com,obama,17-02-2016 19:12,5568,181,36

In [65]:
############## Converting title and headlines into lowercase ##############
data_test['new_title'] = data_test['Title'].apply(lambda x: " ".join(x.lower() for x in x.split()))
data_test['new_headlines'] = data_test['Headline'].apply(lambda x: " ".join(x.lower() for x in x.split()))
data_test['new_title'].head()

0      how millennials are changing the global economy
1       china promises it will keep its economy strong
2              fed eyes increased risks for us economy
3              obama to visit cuba next month: reports
4    white house: obama will not attend justice sca...
Name: new_title, dtype: object

In [66]:
data_test['new_title'].head()

0      how millennials are changing the global economy
1       china promises it will keep its economy strong
2              fed eyes increased risks for us economy
3              obama to visit cuba next month: reports
4    white house: obama will not attend justice sca...
Name: new_title, dtype: object

In [67]:
data_test['new_headlines'].head()

0    but though millennials may have been born into...
1    """china's economic fundamentals have not chan...
2    many federal reserve policymakers saw increase...
3    us president barack obama will make a historic...
4    president barack obama will not attend justice...
Name: new_headlines, dtype: object

In [68]:
################### REMOVING STOP WORDS###################
import nltk
nltk.download('stopwords')
stop = set(stopwords.words('english'))
data_test['new_title'] = data_test['new_title'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))
data_test['new_headlines'] = data_test['new_headlines'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [69]:
data_test.head()

,IDLink,Title,Headline,Source,Topic,PublishDate,Facebook,GooglePlus,LinkedIn,new_title,new_headlines
0,BJ8bLZcYcm,How Millennials Are Changing The Global Economy,But though millennials may have been born into...,Seeking Alpha,economy,17-02-2016 19:09,6,0,3,millennials changing global economy,though millennials may born unlucky economic c...
1,ph8TGKbvNp,China Promises It Will Keep Its Economy Strong,"""""""China's economic fundamentals have not chan...",Fortune,economy,17-02-2016 19:10,5,1,1,china promises keep economy strong,"""""""china's economic fundamentals changed,"""""" z..."
2,qJDgUHX7Ay,Fed eyes increased risks for US economy,Many Federal Reserve policymakers saw increase...,Financial Times,economy,17-02-2016 19:10,45,2,40,fed eyes increased risks us economy,many federal reserve policymakers saw increase...
3,2MVdzsl9s1,Obama to visit Cuba next month: reports,US President Barack Obama will make a historic...,AFP via Yahoo! News,obama,17-02-2016 19:12,17,0,0,obama visit cuba next month: reports,us president barack obama make historic visit ...
4,6QFCqKq50Q,White House: Obama Will Not Attend Justice Sca...,President Barack Obama will not attend Justice...,NBCNews.com,obama,17-02-2016 19:12,5568,181,36,white house: obama attend justice scalia's fun...,president barack obama attend justice antonin ...

In [70]:
data_test['new_headlines'].head()

0    though millennials may born unlucky economic c...
1    """china's economic fundamentals changed,""" z...
2    many federal reserve policymakers saw increase...
3    us president barack obama make historic visit ...
4    president barack obama attend justice antonin ...
Name: new_headlines, dtype: object

In [71]:
########## To remove punctuation #######
data_test['new_title'] = data_test['Title'].str.replace('[^\w\s]','')
data_test['new_headlines'] = data_test['Headline'].str.replace('[^\w\s]','')
data_test.head()

<ipython-input-71-4acb3ed383c8>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  data_test['new_title'] = data_test['Title'].str.replace('[^\w\s]','')
<ipython-input-71-4acb3ed383c8>:3: FutureWarning: The default value of regex will change from True to False in a future version.
  data_test['new_headlines'] = data_test['Headline'].str.replace('[^\w\s]','')

,IDLink,Title,Headline,Source,Topic,PublishDate,Facebook,GooglePlus,LinkedIn,new_title,new_headlines
0,BJ8bLZcYcm,How Millennials Are Changing The Global Economy,But though millennials may have been born into...,Seeking Alpha,economy,17-02-2016 19:09,6,0,3,How Millennials Are Changing The Global Economy,But though millennials may have been born into...
1,ph8TGKbvNp,China Promises It Will Keep Its Economy Strong,"""""""China's economic fundamentals have not chan...",Fortune,economy,17-02-2016 19:10,5,1,1,China Promises It Will Keep Its Economy Strong,Chinas economic fundamentals have not changed ...
2,qJDgUHX7Ay,Fed eyes increased risks for US economy,Many Federal Reserve policymakers saw increase...,Financial Times,economy,17-02-2016 19:10,45,2,40,Fed eyes increased risks for US economy,Many Federal Reserve policymakers saw increase...
3,2MVdzsl9s1,Obama to visit Cuba next month: reports,US President Barack Obama will make a historic...,AFP via Yahoo! News,obama,17-02-2016 19:12,17,0,0,Obama to visit Cuba next month reports,US President Barack Obama will make a historic...
4,6QFCqKq50Q,White House: Obama Will Not Attend Justice Sca...,President Barack Obama will not attend Justice...,NBCNews.com,obama,17-02-2016 19:12,5568,181,36,White House Obama Will Not Attend Justice Scal...,President Barack Obama will not attend Justice...

In [72]:
data_test['new_title'].head()

0      How Millennials Are Changing The Global Economy
1       China Promises It Will Keep Its Economy Strong
2              Fed eyes increased risks for US economy
3               Obama to visit Cuba next month reports
4    White House Obama Will Not Attend Justice Scal...
Name: new_title, dtype: object

In [73]:
data_test['new_headlines'].head()

0    But though millennials may have been born into...
1    Chinas economic fundamentals have not changed ...
2    Many Federal Reserve policymakers saw increase...
3    US President Barack Obama will make a historic...
4    President Barack Obama will not attend Justice...
Name: new_headlines, dtype: object

In [74]:
def remove_emoji(text):
 emoji_pattern = re.compile("["
                        u"\U0001F600-\U0001F64F"  # emoticons
                        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                        u"\U0001F680-\U0001F6FF"  # transport & map symbols
                        u"\U0001F1E0-\U0001F1FF"  # flags 
                        u"\U00002702-\U000027B0"
                        u"\U000024C2-\U0001F251"
                        "]+", flags=re.UNICODE)
 return emoji_pattern.sub(r'', text)
data_test['new_title'] = data_test['Title'].apply(lambda x: remove_emoji(x))
data_test['new_headlines'] = data_test['Headline'].apply(lambda x: remove_emoji(x))

In [75]:
data_test['new_title'].head()

0      How Millennials Are Changing The Global Economy
1       China Promises It Will Keep Its Economy Strong
2              Fed eyes increased risks for US economy
3              Obama to visit Cuba next month: reports
4    White House: Obama Will Not Attend Justice Sca...
Name: new_title, dtype: object

In [76]:
data_test['new_title'].head(20)

0       How Millennials Are Changing The Global Economy
1        China Promises It Will Keep Its Economy Strong
2               Fed eyes increased risks for US economy
3               Obama to visit Cuba next month: reports
4     White House: Obama Will Not Attend Justice Sca...
5     Four in 10 German economists see migrants as d...
6     Microsoft Patches Surface Book And Surface Pro...
7                             Obama’s budget to nowhere
8     Call for Obama to delay supreme court nominati...
9     Obama's Appointment of Acting OPM Chief At Odd...
10    Joy Behar: Obama's 'Color' 'Has Something Do W...
11    Fed flags 'downside risks' to US economy from ...
12    Fed Minutes Lay Bare a Split on Outlook, Rate ...
13    Obama Says He Will Make Historic Trip to Cuba ...
14             Obama to visit Cuba next month - reports
15    Microsoft says its fix for Surface Book, Surfa...
16    What you need to know about Outlook.com as Mic...
17    Mumbai Teacher Makes It To Global Top 10 For U...
18    Is Supply Chain Finance The Solution To Unlock...
19    Do Not Underestimate The Level Of Uncertainty ...
Name: new_title, dtype: object

In [77]:
###############lemmatization using Spacy so that we can count the appearance of each word. Lemmatization removes the grammar tense and transforms each word into its original form. #######
# def space(comment):
#     doc = nlp(comment)
#     return " ".join([token.lemma_ for token in doc])
def space(comment):
    doc = nlp(comment)
    return " ".join([token.lemma_ for token in doc])
data_train['new_headlines']= data_train['new_headlines'].apply(space)
data_train.head()

,IDLink,Topic,Facebook,GooglePlus,LinkedIn,SentimentTitle,SentimentHeadline,new_title,new_headlines
0,Tr3CMgRv1N,obama,-1,-1,-1,0.000000,-0.053300,Obama Lays Wreath Arlington National Cemetery,Obama Lays Wreath Arlington National Cemetery ...
1,Wc81vGp8qZ,economy,-1,-1,-1,0.208333,-0.156386,A Look Health Chinese Economy,"Tim Haywood , investment director business - u..."
2,zNGH03CrZH,economy,-1,-1,-1,-0.425210,0.139754,Nouriel Roubini: Global Economy Not Back 2008,"Nouriel Roubini , NYU professor chairman Roubi..."
3,3sM1H0W8ts,economy,-1,-1,-1,0.000000,0.026064,Finland GDP Expands In Q4,Finland 's economy expand marginally three mon...
4,wUbnxgvqaZ,economy,-1,-1,-1,0.000000,0.141084,"Tourism, govt spending buoys Thai economy January",tourism public spending continue boost economy...

In [78]:
data_test = data_test.drop(['PublishDate','Title','Source','Headline'],axis = 1)
data_test.head(20)

,IDLink,Topic,Facebook,GooglePlus,LinkedIn,new_title,new_headlines
0,BJ8bLZcYcm,economy,6,0,3,How Millennials Are Changing The Global Economy,But though millennials may have been born into...
1,ph8TGKbvNp,economy,5,1,1,China Promises It Will Keep Its Economy Strong,"""""""China's economic fundamentals have not chan..."
2,qJDgUHX7Ay,economy,45,2,40,Fed eyes increased risks for US economy,Many Federal Reserve policymakers saw increase...
3,2MVdzsl9s1,obama,17,0,0,Obama to visit Cuba next month: reports,US President Barack Obama will make a historic...
4,6QFCqKq50Q,obama,5568,181,36,White House: Obama Will Not Attend Justice Sca...,President Barack Obama will not attend Justice...
5,50Gqd3bxAP,economy,11,1,0,Four in 10 German economists see migrants as d...,BERLIN Four in ten German economists believe t...
6,4XFbet5nuU,microsoft,4,2,1,Microsoft Patches Surface Book And Surface Pro...,"When I reviewed the Surface Book, there were a..."
7,EHxfGLWj4D,obama,0,0,0,Obama’s budget to nowhere,Barack Obama’s last budget is nothing if not i...
8,GIgCdpoXQg,obama,289,121,5,Call for Obama to delay supreme court nominati...,Republican calls for Barack Obama to refrain f...
9,FsU13jkSUN,obama,12,0,0,Obama's Appointment of Acting OPM Chief At Odd...,The problem essentially happened because Presi...
10,cH6jw5NJZG,obama,1085,9,0,Joy Behar: Obama's 'Color' 'Has Something Do W...,"ABC's """"""The View"""""" co-host Joy Behar argued ..."
11,1ZGtTCOMob,economy,2,1,1,Fed flags 'downside risks' to US economy from ...,Federal Reserve policymakers worried last mont...
12,tLEIzoyy1U,economy,79,0,46,"Fed Minutes Lay Bare a Split on Outlook, Rate ...",uncertainty about the outlook for inflation a...
13,LT0vJ9e8RL,obama,-1,-1,-1,Obama Says He Will Make Historic Trip to Cuba ...,President Barack Obama waves as he walks out o...
14,fLhSewI7hl,obama,2,0,0,Obama to visit Cuba next month - reports,US President Barack Obama will make a historic...
15,BKmMCCyI24,microsoft,0,0,0,"Microsoft says its fix for Surface Book, Surfa...","It seems like Microsoft has finally, completel..."
16,zLfTXlitf4,microsoft,0,0,0,What you need to know about Outlook.com as Mic...,"Since May 2015, Microsoft’s revamped Outlook.c..."
17,D1UGJpSrZZ,palestine,0,0,0,Mumbai Teacher Makes It To Global Top 10 For U...,An Indian teacher who runs a not-for-profit sc...
18,N1XTITfsp6,economy,17,2,85,Is Supply Chain Finance The Solution To Unlock...,It seems there is no end to the categories and...
19,0V9oxMjhMt,economy,1,0,12,Do Not Underestimate The Level Of Uncertainty ...,"Since Q2-2015, S&amp;P500 volatility, as measu..."

In [79]:
# from sklearn import metrics
# def print_error(X_test, y_test, model_name):
#   prediction = model_name.predict(X_test)
#   print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, prediction))
#   print('Mean Squared Error:', metrics.mean_squared_error(y_test, prediction))
#   print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, prediction)))

############ TESTING  PART ##################
############ NOT INCLUDED IN THE MODEL ############

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

CV = CountVectorizer()
CV_features = CV.fit_transform(data_test['new_title'])
CV_features

In [ ]:
from sklearn.preprocessing import MaxAbsScaler
scaler = MaxAbsScaler()
vectorizer = TfidfVectorizer()
X_test = vectorizer.fit_transform(data_train['new_title'])
X_test=scaler.fit_transform(X_test)

In [ ]:
X_test.sort_indices()
prediction = model.predict(X_test)

In [ ]:
clf.predict(X_test)

In [ ]:
train_data,train_labels=data_train['new_title'],data_train['SentimentTitle']
# test_data, test_labels = data_test['new_title'],data_test['SentimentTitle']

from sklearn.feature_extraction.text import CountVectorizer

CV = CountVectorizer()
CV_features = CV.fit_transform(train_data)
CV_features.shape

In [ ]:
CV_features[0]

In [ ]:
CV_features[0].todense()

In [ ]:
df = pd.DataFrame(CV_features.todense() )
df

In [ ]:
df.size/1e6

In [ ]:
import numpy as np
np.count_nonzero(df)

In [ ]:
100*np.count_nonzero(df)/df.size

In [ ]:
print(CV.get_feature_names_out()[:100])

In [ ]:
len(CV.get_feature_names_out())

In [ ]:
CV.inverse_transform(np.asarray(CV_features[10].todense()))

In [ ]:
from sklearn.model_selection import train_test_split
train, xtest, ytrain, ytest = train_test_split(X, y.iloc[:,1], test_size=1/3,
  random_state=85, stratify=y.iloc[:,1])
X_train, X_test, y_train, y_test = train_test_split(CV_features, train_labels, test_size=0.25, stratify=train_labels, random_state=42)

In [ ]:
# Y_train = pd.DataFrame(data = data_train.iloc[:, 9].values, columns = ['target'])
# data_train.head()

# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(data_train, Y_train, test_size=0.2, random_state=42)

# X_train.shape

In [ ]:
# from sklearn.linear_model import LogisticRegression
# from sklearn.metrics import accuracy_score
# from sklearnex import patch_sklearn

# patch_sklearn()

# estimator = LogisticRegression(max_iter=1000, n_jobs=-1, solver='saga')

# # Train the model
# estimator.fit(X_train, y_train)
# print(X_train)
# # Make predictions on the testing set
# y_pred = estimator.predict(X_test)

# # Evaluate the model performance
# accuracy = accuracy_score(y_test, y_pred)
# print('Accuracy:', accuracy)
# y_pred

In [ ]:
# import os
# from sklearn.datasets import make_classification
# from sklearn.model_selection import train_test_split
# from sklearn.ensemble import RandomForestClassifier

# # Generate a toy classification dataset
# X, y = make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=42)

# # Split the dataset into training and test sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# # Train a random forest classifier with the scikit-learn backend
# clf = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=42)
# clf.fit(X_train, y_train)

# # Switch to the daal4py backend during training
# os.environ['D4P_BACKEND'] = 'sklearn'
# from daal4py.sklearn.ensemble import RandomForestClassifier as D4PRandomForestClassifier

# d4p_clf = D4PRandomForestClassifier(n_estimators=100, max_depth=2, random_state=42)
# d4p_clf.fit(X_train, y_train)

# # Evaluate the performance of the scikit-learn and daal4py classifiers on the test set
# print('Scikit-learn classifier accuracy:', clf.score(X_test, y_test))
# print('daal4py classifier accuracy:', d4p_clf.score(X_test, y_test))
# y_test